apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-http-readinessprobe
  labels:
    app: kuber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server-default
  template:
    metadata:
      labels:
        app: http-server-default
    spec:
      containers:
      - name: kuber-app
        image: davidovskiea/kuber
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5