apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dep
  labels:
    app: kuber
spec:
  #replicas: 2
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kuber
          - http-server
      #- key: env
      #  operator: Exists
  template:
    metadata:
      labels:
        app: http-server
      #  env: dev
    spec:
      containers:
      - name: kuber-app
        image: davidovskiea/kuber
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /randompath
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /randompath
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-lb
spec:
  externalTrafficPolicy: Local
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: kuber-dep
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80